<?php 

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('indexheader');
?>

<div class="container">
	<div class="row">
		<article class="col-xs-12 maincontent">
			<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
				<div class="panel panel-default" style="margin-top: 50px; margin-bottom: 100px">
					<div class="panel-body">
						<h3 class="thin text-center">Registo</h3>

						<hr>
						
						<form method="POST" action="<?= URL::toRoute('home/register')?>">
							<div class="top-margin">
								<label>Nome Completo<span class="text-danger">*</span></label>
								<input type="text" class="form-control" name="nome" required="required">
							</div>
							<div class="top-margin">
								<label>Data de Nascimento <span class="text-danger">*</span></label>
								<input type="date" class="form-control" name="birthdate" required="required">
							</div>
							<div class="top-margin">
								<label>Email<span class="text-danger">*</span></label>
								<input type="email" class="form-control" name="email" required="required">
							</div>
							<div class="top-margin">
								<label>Nome de Utilizador<span class="text-danger">*</span></label>
								<input type="text" class="form-control" name="username" required="required">
							</div>
							<div class="top-margin">
								<label>Palavra-Passe <span class="text-danger">*</span></label>
								<input type="password" class="form-control" name="password" required="required">
							</div>

							<hr>

							<div class="row">
								<div class="col-lg-8">
								</div>
								<div class="col-lg-4 text-right">
									<button class="btn btn-action" type="submit">Criar</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</article>
	</div>
</div>

<?php Layout::includeLayout('footer') ?>