<footer id="footer" class="top-space">

<div class="footer2">
    <div class="container">
        <div class="row">
                <div class="col-md-3 widget">
                    <div class="widget-body">
                        <p class="text-left">
                            Programação Web - Servidor<br>TeSP Programação e Sistemas de Informação
                        </p>
                    </div>
                </div>

            <div class="col-md-9 widget">
                <div class="widget-body">
                    <p class="text-right">
                        Copyright &copy; 2016-2017, João Porêlo, Leonardo Domingues, Cristiano Luís.<br>Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a>
                    </p>
                </div>
            </div>
        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>