<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <!--<meta name="author"      content="Silvio Priem Mendes, PhD">-->

    <title>Weblogic MVC</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/custom.css')?>">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body class="home">

<div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="<?= URL::toRoute('game/index')?>"><img src="<?= Asset::image('logo.png')?>" alt="WEBlogic MVC"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li class="active"><a href="<?= URL::toRoute('home/jackpot')?>">Jackpot</a></li>
                <li><a href="<?= URL::toRoute('game/index')?>">Jogar</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Conta<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="active"><a href="<?= URL::toRoute('user/perfil')?>">Perfil</a></li>
                        <li><a href="<?= Url::toRoute('user/movimentos')?>">Movimentos</a></li>
                        <li><a href="<?= Url::toRoute('user/carregamento')?>">Carregar</a></li>
                    </ul>
                </li>
                <li><a class="btn" href="<?= URL::toRoute('user/logout')?>">Sair</a></li>
            </ul>
        </div>
    </div>
</div>
