<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('userheader');
?>
    
<div class="jumbotron top-space">
    <h4><strong> TO-DO</strong> 
        <h5>
            <ul>
                <li><strong>Página Inicial</strong> Mostrar algo de útil ao user que entrar aqui</li>
                <li><strong>Restantes páginas</strong> Criar as restantes páginas</li>
                <li><strong>Router.php</strong> Atualizar o router com os novos caminhos</li>
                <li><strong>Controladores, modelos, etc</strong> Fazer o restante código</li>
            </ul>
        </h5>
</div>

<a href="<?= URL::toRoute('game/index')?>">JOGO</a>

</div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>