<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use Tracy\Debugger;

Layout::includeLayout('userheader');

$movimentos = Data::get('movimentos');

?>

<div class="container">
	<h1 class="thin text-center" style="margin-top: 50px"><b>Movimentos</b></h1>
	
	<div class="row" style="margin-top: 50px; margin-bottom: 285px">
		<div class="col-md-3"></div>
			<div class="col-md-6">
				<table class="table table-striped table-hover table-bordered table-condensed">
					<thead>
						<tr>
							<td align='center' width="120">Data e Hora</td>
							<td align='center' width="50">Tipo</td>
							<td align='center' width="90">Descrição</td>
                            <td align='center' width="50">Valor</td>
                            <td align='center' width="80">Saldo Final</td>
						</tr>
					</thead>
					<tbody>

					<?php foreach ($movimentos as $movimento) { 
                        $date = $movimento->data
                    ?>
                        <tr>
                            <td><?=$date->format('Y-m-d H:i:s')?></td>
                            <td><?=$movimento->tipo?></td>
                            <td><?=$movimento->descricao?></td>
                            <td><?=$movimento->valor?></td>
                            <td><?=$movimento->saldo?></td>
                        </tr>

                    <?php } ?>

					</tbody>
				</table>
			</div>
		<div class="col-md-3"></div>
	</div>
</div>

<?php Layout::includeLayout('footer') ?>