<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;

$hand = Data::get('hand');
$title = Data::get('title');

?>
<!-- ----------------------------------------------------- -->

<link rel="stylesheet" href="<?= Asset::css('custom.css')?>" media="screen" >

<!-- ----------------------------------------------------- -->

<h1 align='center' style="margin-top: 0px"><?=$title?></h1>

<table align='center'>
	<tr>

	<?php foreach ($hand as $id => $image) { ?>
			<td width="140">
				<input id=<?=$id?> type='image' class="card" src="<?=Asset::image('Cards/cardBack_blue5.png') ?>" onclick="ChangeCardValue('c<?=$id?>', 'p<?=$id?>')" /> 
				<img id='o<?=$id?>' src="<?=Asset::image('Cards/'. $image.'') ?>" hidden='hidden'>
			</td>
			<td width="10"></td>
	<?php }?>

	</tr>
</table>

<audio id="flipCard" src="<?=Asset::html('Sounds/cardSlide1.wav')?>"></audio>

<!-- ----------------------------------------------------- -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="<?= Asset::js('custom.js')?>"></script>

<!-- ----------------------------------------------------- -->